package com.spring.demo.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class TradeOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.orderId
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private Long orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.buyerId
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private Long buyerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.buyerNick
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private String buyernick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.payId
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private Long payid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.status
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.refundStatus
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private Integer refundstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.billAmount
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private BigDecimal billamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.discountAmount
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private BigDecimal discountamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.marketPrice
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private BigDecimal marketprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.taxFee
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private BigDecimal taxfee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.logisticsFee
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private BigDecimal logisticsfee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.orderPayId
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private Long orderpayid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.payType
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private Byte paytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.orderSource
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private Byte ordersource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.orderType
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private Byte ordertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.logisticsType
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private Byte logisticstype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.shopId
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private Long shopid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.businessId
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private Long businessid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.isAfter
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private Byte isafter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.feature
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private String feature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.gmtCreate
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private Date gmtcreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.gmtPay
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private Date gmtpay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.gmtDeliver
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private Date gmtdeliver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.gmtReceived
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private Date gmtreceived;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.gmtConfirm
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private Date gmtconfirm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.receiverCountry
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private String receivercountry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.gmtModified
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private Date gmtmodified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.receiverProvince
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private String receiverprovince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.receiverCity
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private String receivercity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.receiverArea
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private String receiverarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.receiverAddress
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private String receiveraddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.receiverMobile
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private String receivermobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.receiverTelephone
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private String receivertelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.receiverName
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private String receivername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.receiverPostCode
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private String receiverpostcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.refundCountry
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private String refundcountry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.refundProvince
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private String refundprovince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.refundCity
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private String refundcity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.refundArea
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private String refundarea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.refundAddress
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private String refundaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.refundMobile
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private String refundmobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.refundTelephone
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private String refundtelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.refundPostCode
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private String refundpostcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.refundName
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private String refundname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.channelId
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private String channelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.flag
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private Long flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.flagRemark
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private String flagremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.actualAmount
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private BigDecimal actualamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_order.couponIds
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    private String couponids;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.orderId
     *
     * @return the value of trade_order.orderId
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public Long getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.orderId
     *
     * @param orderid the value for trade_order.orderId
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setOrderid(Long orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.buyerId
     *
     * @return the value of trade_order.buyerId
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public Long getBuyerid() {
        return buyerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.buyerId
     *
     * @param buyerid the value for trade_order.buyerId
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setBuyerid(Long buyerid) {
        this.buyerid = buyerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.buyerNick
     *
     * @return the value of trade_order.buyerNick
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public String getBuyernick() {
        return buyernick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.buyerNick
     *
     * @param buyernick the value for trade_order.buyerNick
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setBuyernick(String buyernick) {
        this.buyernick = buyernick == null ? null : buyernick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.payId
     *
     * @return the value of trade_order.payId
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public Long getPayid() {
        return payid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.payId
     *
     * @param payid the value for trade_order.payId
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setPayid(Long payid) {
        this.payid = payid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.status
     *
     * @return the value of trade_order.status
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.status
     *
     * @param status the value for trade_order.status
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.refundStatus
     *
     * @return the value of trade_order.refundStatus
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public Integer getRefundstatus() {
        return refundstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.refundStatus
     *
     * @param refundstatus the value for trade_order.refundStatus
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setRefundstatus(Integer refundstatus) {
        this.refundstatus = refundstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.billAmount
     *
     * @return the value of trade_order.billAmount
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public BigDecimal getBillamount() {
        return billamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.billAmount
     *
     * @param billamount the value for trade_order.billAmount
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setBillamount(BigDecimal billamount) {
        this.billamount = billamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.discountAmount
     *
     * @return the value of trade_order.discountAmount
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public BigDecimal getDiscountamount() {
        return discountamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.discountAmount
     *
     * @param discountamount the value for trade_order.discountAmount
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setDiscountamount(BigDecimal discountamount) {
        this.discountamount = discountamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.marketPrice
     *
     * @return the value of trade_order.marketPrice
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public BigDecimal getMarketprice() {
        return marketprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.marketPrice
     *
     * @param marketprice the value for trade_order.marketPrice
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setMarketprice(BigDecimal marketprice) {
        this.marketprice = marketprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.taxFee
     *
     * @return the value of trade_order.taxFee
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public BigDecimal getTaxfee() {
        return taxfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.taxFee
     *
     * @param taxfee the value for trade_order.taxFee
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setTaxfee(BigDecimal taxfee) {
        this.taxfee = taxfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.logisticsFee
     *
     * @return the value of trade_order.logisticsFee
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public BigDecimal getLogisticsfee() {
        return logisticsfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.logisticsFee
     *
     * @param logisticsfee the value for trade_order.logisticsFee
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setLogisticsfee(BigDecimal logisticsfee) {
        this.logisticsfee = logisticsfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.orderPayId
     *
     * @return the value of trade_order.orderPayId
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public Long getOrderpayid() {
        return orderpayid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.orderPayId
     *
     * @param orderpayid the value for trade_order.orderPayId
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setOrderpayid(Long orderpayid) {
        this.orderpayid = orderpayid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.payType
     *
     * @return the value of trade_order.payType
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public Byte getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.payType
     *
     * @param paytype the value for trade_order.payType
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setPaytype(Byte paytype) {
        this.paytype = paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.orderSource
     *
     * @return the value of trade_order.orderSource
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public Byte getOrdersource() {
        return ordersource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.orderSource
     *
     * @param ordersource the value for trade_order.orderSource
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setOrdersource(Byte ordersource) {
        this.ordersource = ordersource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.orderType
     *
     * @return the value of trade_order.orderType
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public Byte getOrdertype() {
        return ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.orderType
     *
     * @param ordertype the value for trade_order.orderType
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setOrdertype(Byte ordertype) {
        this.ordertype = ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.logisticsType
     *
     * @return the value of trade_order.logisticsType
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public Byte getLogisticstype() {
        return logisticstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.logisticsType
     *
     * @param logisticstype the value for trade_order.logisticsType
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setLogisticstype(Byte logisticstype) {
        this.logisticstype = logisticstype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.shopId
     *
     * @return the value of trade_order.shopId
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public Long getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.shopId
     *
     * @param shopid the value for trade_order.shopId
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setShopid(Long shopid) {
        this.shopid = shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.businessId
     *
     * @return the value of trade_order.businessId
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public Long getBusinessid() {
        return businessid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.businessId
     *
     * @param businessid the value for trade_order.businessId
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setBusinessid(Long businessid) {
        this.businessid = businessid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.isAfter
     *
     * @return the value of trade_order.isAfter
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public Byte getIsafter() {
        return isafter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.isAfter
     *
     * @param isafter the value for trade_order.isAfter
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setIsafter(Byte isafter) {
        this.isafter = isafter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.feature
     *
     * @return the value of trade_order.feature
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public String getFeature() {
        return feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.feature
     *
     * @param feature the value for trade_order.feature
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setFeature(String feature) {
        this.feature = feature == null ? null : feature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.gmtCreate
     *
     * @return the value of trade_order.gmtCreate
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public Date getGmtcreate() {
        return gmtcreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.gmtCreate
     *
     * @param gmtcreate the value for trade_order.gmtCreate
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setGmtcreate(Date gmtcreate) {
        this.gmtcreate = gmtcreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.gmtPay
     *
     * @return the value of trade_order.gmtPay
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public Date getGmtpay() {
        return gmtpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.gmtPay
     *
     * @param gmtpay the value for trade_order.gmtPay
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setGmtpay(Date gmtpay) {
        this.gmtpay = gmtpay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.gmtDeliver
     *
     * @return the value of trade_order.gmtDeliver
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public Date getGmtdeliver() {
        return gmtdeliver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.gmtDeliver
     *
     * @param gmtdeliver the value for trade_order.gmtDeliver
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setGmtdeliver(Date gmtdeliver) {
        this.gmtdeliver = gmtdeliver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.gmtReceived
     *
     * @return the value of trade_order.gmtReceived
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public Date getGmtreceived() {
        return gmtreceived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.gmtReceived
     *
     * @param gmtreceived the value for trade_order.gmtReceived
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setGmtreceived(Date gmtreceived) {
        this.gmtreceived = gmtreceived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.gmtConfirm
     *
     * @return the value of trade_order.gmtConfirm
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public Date getGmtconfirm() {
        return gmtconfirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.gmtConfirm
     *
     * @param gmtconfirm the value for trade_order.gmtConfirm
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setGmtconfirm(Date gmtconfirm) {
        this.gmtconfirm = gmtconfirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.receiverCountry
     *
     * @return the value of trade_order.receiverCountry
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public String getReceivercountry() {
        return receivercountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.receiverCountry
     *
     * @param receivercountry the value for trade_order.receiverCountry
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setReceivercountry(String receivercountry) {
        this.receivercountry = receivercountry == null ? null : receivercountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.gmtModified
     *
     * @return the value of trade_order.gmtModified
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public Date getGmtmodified() {
        return gmtmodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.gmtModified
     *
     * @param gmtmodified the value for trade_order.gmtModified
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setGmtmodified(Date gmtmodified) {
        this.gmtmodified = gmtmodified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.receiverProvince
     *
     * @return the value of trade_order.receiverProvince
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public String getReceiverprovince() {
        return receiverprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.receiverProvince
     *
     * @param receiverprovince the value for trade_order.receiverProvince
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setReceiverprovince(String receiverprovince) {
        this.receiverprovince = receiverprovince == null ? null : receiverprovince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.receiverCity
     *
     * @return the value of trade_order.receiverCity
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public String getReceivercity() {
        return receivercity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.receiverCity
     *
     * @param receivercity the value for trade_order.receiverCity
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setReceivercity(String receivercity) {
        this.receivercity = receivercity == null ? null : receivercity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.receiverArea
     *
     * @return the value of trade_order.receiverArea
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public String getReceiverarea() {
        return receiverarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.receiverArea
     *
     * @param receiverarea the value for trade_order.receiverArea
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setReceiverarea(String receiverarea) {
        this.receiverarea = receiverarea == null ? null : receiverarea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.receiverAddress
     *
     * @return the value of trade_order.receiverAddress
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public String getReceiveraddress() {
        return receiveraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.receiverAddress
     *
     * @param receiveraddress the value for trade_order.receiverAddress
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setReceiveraddress(String receiveraddress) {
        this.receiveraddress = receiveraddress == null ? null : receiveraddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.receiverMobile
     *
     * @return the value of trade_order.receiverMobile
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public String getReceivermobile() {
        return receivermobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.receiverMobile
     *
     * @param receivermobile the value for trade_order.receiverMobile
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setReceivermobile(String receivermobile) {
        this.receivermobile = receivermobile == null ? null : receivermobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.receiverTelephone
     *
     * @return the value of trade_order.receiverTelephone
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public String getReceivertelephone() {
        return receivertelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.receiverTelephone
     *
     * @param receivertelephone the value for trade_order.receiverTelephone
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setReceivertelephone(String receivertelephone) {
        this.receivertelephone = receivertelephone == null ? null : receivertelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.receiverName
     *
     * @return the value of trade_order.receiverName
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public String getReceivername() {
        return receivername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.receiverName
     *
     * @param receivername the value for trade_order.receiverName
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setReceivername(String receivername) {
        this.receivername = receivername == null ? null : receivername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.receiverPostCode
     *
     * @return the value of trade_order.receiverPostCode
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public String getReceiverpostcode() {
        return receiverpostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.receiverPostCode
     *
     * @param receiverpostcode the value for trade_order.receiverPostCode
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setReceiverpostcode(String receiverpostcode) {
        this.receiverpostcode = receiverpostcode == null ? null : receiverpostcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.refundCountry
     *
     * @return the value of trade_order.refundCountry
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public String getRefundcountry() {
        return refundcountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.refundCountry
     *
     * @param refundcountry the value for trade_order.refundCountry
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setRefundcountry(String refundcountry) {
        this.refundcountry = refundcountry == null ? null : refundcountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.refundProvince
     *
     * @return the value of trade_order.refundProvince
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public String getRefundprovince() {
        return refundprovince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.refundProvince
     *
     * @param refundprovince the value for trade_order.refundProvince
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setRefundprovince(String refundprovince) {
        this.refundprovince = refundprovince == null ? null : refundprovince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.refundCity
     *
     * @return the value of trade_order.refundCity
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public String getRefundcity() {
        return refundcity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.refundCity
     *
     * @param refundcity the value for trade_order.refundCity
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setRefundcity(String refundcity) {
        this.refundcity = refundcity == null ? null : refundcity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.refundArea
     *
     * @return the value of trade_order.refundArea
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public String getRefundarea() {
        return refundarea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.refundArea
     *
     * @param refundarea the value for trade_order.refundArea
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setRefundarea(String refundarea) {
        this.refundarea = refundarea == null ? null : refundarea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.refundAddress
     *
     * @return the value of trade_order.refundAddress
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public String getRefundaddress() {
        return refundaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.refundAddress
     *
     * @param refundaddress the value for trade_order.refundAddress
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setRefundaddress(String refundaddress) {
        this.refundaddress = refundaddress == null ? null : refundaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.refundMobile
     *
     * @return the value of trade_order.refundMobile
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public String getRefundmobile() {
        return refundmobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.refundMobile
     *
     * @param refundmobile the value for trade_order.refundMobile
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setRefundmobile(String refundmobile) {
        this.refundmobile = refundmobile == null ? null : refundmobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.refundTelephone
     *
     * @return the value of trade_order.refundTelephone
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public String getRefundtelephone() {
        return refundtelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.refundTelephone
     *
     * @param refundtelephone the value for trade_order.refundTelephone
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setRefundtelephone(String refundtelephone) {
        this.refundtelephone = refundtelephone == null ? null : refundtelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.refundPostCode
     *
     * @return the value of trade_order.refundPostCode
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public String getRefundpostcode() {
        return refundpostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.refundPostCode
     *
     * @param refundpostcode the value for trade_order.refundPostCode
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setRefundpostcode(String refundpostcode) {
        this.refundpostcode = refundpostcode == null ? null : refundpostcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.refundName
     *
     * @return the value of trade_order.refundName
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public String getRefundname() {
        return refundname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.refundName
     *
     * @param refundname the value for trade_order.refundName
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setRefundname(String refundname) {
        this.refundname = refundname == null ? null : refundname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.channelId
     *
     * @return the value of trade_order.channelId
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public String getChannelid() {
        return channelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.channelId
     *
     * @param channelid the value for trade_order.channelId
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setChannelid(String channelid) {
        this.channelid = channelid == null ? null : channelid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.flag
     *
     * @return the value of trade_order.flag
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public Long getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.flag
     *
     * @param flag the value for trade_order.flag
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setFlag(Long flag) {
        this.flag = flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.flagRemark
     *
     * @return the value of trade_order.flagRemark
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public String getFlagremark() {
        return flagremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.flagRemark
     *
     * @param flagremark the value for trade_order.flagRemark
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setFlagremark(String flagremark) {
        this.flagremark = flagremark == null ? null : flagremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.actualAmount
     *
     * @return the value of trade_order.actualAmount
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public BigDecimal getActualamount() {
        return actualamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.actualAmount
     *
     * @param actualamount the value for trade_order.actualAmount
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setActualamount(BigDecimal actualamount) {
        this.actualamount = actualamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_order.couponIds
     *
     * @return the value of trade_order.couponIds
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public String getCouponids() {
        return couponids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_order.couponIds
     *
     * @param couponids the value for trade_order.couponIds
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    public void setCouponids(String couponids) {
        this.couponids = couponids == null ? null : couponids.trim();
    }
}