package com.spring.demo.mybatis.dao;

import com.spring.demo.mybatis.model.TradeSubOrder;
import com.spring.demo.mybatis.model.TradeSubOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradeSubOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_sub_order
     *
     * @mbggenerated Wed Jul 19 15:54:55 CST 2017
     */
    int countByExample(TradeSubOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_sub_order
     *
     * @mbggenerated Wed Jul 19 15:54:55 CST 2017
     */
    int deleteByExample(TradeSubOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_sub_order
     *
     * @mbggenerated Wed Jul 19 15:54:55 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_sub_order
     *
     * @mbggenerated Wed Jul 19 15:54:55 CST 2017
     */
    int insert(TradeSubOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_sub_order
     *
     * @mbggenerated Wed Jul 19 15:54:55 CST 2017
     */
    int insertSelective(TradeSubOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_sub_order
     *
     * @mbggenerated Wed Jul 19 15:54:55 CST 2017
     */
    List<TradeSubOrder> selectByExample(TradeSubOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_sub_order
     *
     * @mbggenerated Wed Jul 19 15:54:55 CST 2017
     */
    TradeSubOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_sub_order
     *
     * @mbggenerated Wed Jul 19 15:54:55 CST 2017
     */
    int updateByExampleSelective(@Param("record") TradeSubOrder record, @Param("example") TradeSubOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_sub_order
     *
     * @mbggenerated Wed Jul 19 15:54:55 CST 2017
     */
    int updateByExample(@Param("record") TradeSubOrder record, @Param("example") TradeSubOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_sub_order
     *
     * @mbggenerated Wed Jul 19 15:54:55 CST 2017
     */
    int updateByPrimaryKeySelective(TradeSubOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_sub_order
     *
     * @mbggenerated Wed Jul 19 15:54:55 CST 2017
     */
    int updateByPrimaryKey(TradeSubOrder record);
}