package com.spring.demo.mybatis.dao;

import com.spring.demo.mybatis.model.TradeOrder;
import com.spring.demo.mybatis.model.TradeOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TradeOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    int countByExample(TradeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    int deleteByExample(TradeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    int deleteByPrimaryKey(Long orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    int insert(TradeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    int insertSelective(TradeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    List<TradeOrder> selectByExample(TradeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    TradeOrder selectByPrimaryKey(Long orderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    int updateByExampleSelective(@Param("record") TradeOrder record, @Param("example") TradeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    int updateByExample(@Param("record") TradeOrder record, @Param("example") TradeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    int updateByPrimaryKeySelective(TradeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_order
     *
     * @mbggenerated Wed Jul 19 16:06:36 CST 2017
     */
    int updateByPrimaryKey(TradeOrder record);
}